#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Rails.application.require_environment!

class ResqueWorkerDaemon < DaemonSpawn::Base
  def start(args)
    @worker = Resque::Worker.new('APP_NAME', 'mailers', 'default')
    @worker.verbose = true
    @worker.work(5)
  end

  def stop
    @worker.try(:shutdown)
  end
end

LOG_FNAME = 'resque_worker.log'

log_base = File.join(Rails.root, 'log')
log_file = File.join(log_base, LOG_FNAME)
if File.exist?(log_file) then
  File.delete(log_file)
end

require 'fileutils'

pid_base = File.join(Rails.root, 'tmp', 'pids')
unless File.exist?(pid_base)
  FileUtils.mkdir_p(pid_base)
end
pid_path = File.join(pid_base, 'resque_worker.pid')

ResqueWorkerDaemon.spawn!({
  working_dir: Rails.root, 
  pid_file: pid_path, 
  log_file: log_file, 
  sync_log: true, 
  singleton: true, 
  signal: :QUIT, 
  processes: 5
})

